I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/main.rpy", line 8, in script call
    call introdaction
  File "game/chapters/01/introduction.rpy", line 6, in script
    scene bg ege test
Exception: Image 'bg ege' does not accept attributes 'test'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/main.rpy", line 8, in script call
    call introdaction
  File "game/chapters/01/introduction.rpy", line 6, in script
    scene bg ege test
  File "H:\URFU\Informatics\VisualNovel\renpy-8.0.3-sdk\renpy\ast.py", line 1542, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "H:\URFU\Informatics\VisualNovel\renpy-8.0.3-sdk\renpy\ast.py", line 1371, in show_imspec
    renpy.config.show(name,
  File "H:\URFU\Informatics\VisualNovel\renpy-8.0.3-sdk\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "H:\URFU\Informatics\VisualNovel\renpy-8.0.3-sdk\renpy\display\image.py", line 414, in find_target
    self.target = target._duplicate(a)
  File "H:\URFU\Informatics\VisualNovel\renpy-8.0.3-sdk\renpy\display\core.py", line 397, in _duplicate
    args.extraneous()
  File "H:\URFU\Informatics\VisualNovel\renpy-8.0.3-sdk\renpy\display\core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'bg ege' does not accept attributes 'test'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Novel 1.0
Wed Oct 26 20:57:29 2022
